version: "3.4"
services:
  mapisto-api:
    build: .
    ports:
      - "7070:5000"
    volumes:
      - ./src:/app/src
    tty: true
    env_file:
      - conf.test.env
  database_test:
    image: postgres:12-alpine
    ports: 
      - 5433:5432
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
