version: "3.4"
services:
  mapisto-api:
    build: .
    ports:
      - "8080:5000"
    volumes:
      - ./src:/app/src
    environment:
      FLASK_DEBUG: 1
    env_file:
      - conf.env
  database:
    image: postgres:12-alpine
    ports: 
      - 5433:5432
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
    