version: "3.4"
services:
  mapisto-api:
    build:
      context: .
      target: base_env
    ports:
      - "8080:5000"
    volumes:
      - ./src:/app/src
    environment:
      MAPISTO_DB_HOST: database
    env_file:
      - conf.env
  database:
    image: postgres:12-alpine
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
